(cl:in-package :cl-user)

(declaim 
 (ftype (function (t t) *) mcs::|(SETF CLASS-DIRECT-METHODS)|)
 (ftype (function (t t) *) mcs::|(SETF CLASS-DIRECT-SUBCLASSES)|)
 (ftype (function (t t) *) mcs::|(SETF CLASS-DIRECT-SUPERCLASSES)|)
 (ftype (function (t t) *) mcs::|(SETF CLASS-EFFECTIVE-METHODS)|)
 (ftype (function (t t) *) mcs::|(SETF CLASS-INITIAL-PLIST)|)
 (ftype (function (t t) *) mcs::|(SETF FINALIZEDP)|)
 (ftype (function (t t t) (values mcs::mcs% &optional)) 
        mcs::check-for-existing-gfn)
 (ftype (function (t) *) mcs:class-direct-methods)
 (ftype (function (t) *) mcs:class-direct-superclasses)
 (ftype (function (t) *) mcs::class-effective-methods)
 (ftype (function (t) *) mcs::class-initial-plist)
 (ftype (function (t) *) mcs:class-name)
 (ftype (function (t) *) mcs:generic-function-name)
 (ftype (function (t) *) mcs:method-name)
 (ftype (function (t) *) mcs:method-qualifiers)
 (ftype (function (t) *) mcs:method-specializers))
